//POSTS

export const SET_POSTS = 'SET_POSTS'
export const SET_SELECTED_POST = 'SET_SELECTED_POST'
export const ADD_NEW_POST = 'ADD_NEW_POST'
export const DELETE_POST = 'DELETE_POST'
export const SET_EDITING = 'SET_EDITING'
export const SET_UPDATED = 'SET_UPDATED'
export const SET_NEW_POST = 'SET_NEW_POST'
export const SET_FILTERED_POSTS = 'SET_FILTERED_POSTS'
export const SET_FILTER = 'SET_FILTER'

//COMMENTS

export const SET_COMMENTS = 'SET_COMMENTS'
export const DELETE_COMMENT = 'DELETE_COMMENT'

//AUTH

export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_LOGIN_CREDS = 'SET_LOGIN_CREDS'
export const SET_NEW_USER = 'SET_NEW_USER'
export const SET_REGISTERED = 'SET_REGISTERED'
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_FILE = 'SET_FILE'
